services:
  operador:
    build: ./
    command: python -u client.py
    container_name: "operador"
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=${SERVER_HOST:?SERVER_HOST nao definido. Ex: export SERVER_HOST=192.168.1.10}