services:
  sensor-temp:
    build: ./
    command: python -u sensor_temp.py
    environment:
      SERVER_HOST: ${SERVER_HOST:-servidor}

  sensor-umid:
    build: ./
    command: python -u sensor_umid.py
    environment:
      SERVER_HOST: ${SERVER_HOST:-servidor}