services:
  sensor-temp:
    build: ./
    command: python -u sensor_temp.py
    environment:
      - SERVER_HOST=${SERVER_HOST:?SERVER_HOST nao definido. Ex: export SERVER_HOST=192.168.1.10}

  sensor-umid:
    build: ./
    command: python -u sensor_umid.py
    environment:
      - SERVER_HOST=${SERVER_HOST:?SERVER_HOST nao definido. Ex: export SERVER_HOST=192.168.1.10}