services:
  atuador-vent:
    build: ./
    command: python -u atuador_vent.py
    container_name: "atuador-vent"
    environment:
      - SERVER_HOST=${SERVER_HOST:-servidor}
    networks:
      - iot_net

  atuador-umid:
    build: ./
    command: python -u atuador_umid.py
    container_name: "atuador-umid"
    environment:
      - SERVER_HOST=${SERVER_HOST:-servidor}
    networks:
      - iot_net

networks:
  iot_net:
    external: true
    name: iot_net